name: GitHub Sponsors Profile Review
description: Please review my GitHub Sponsors profile on a livestream
title: "[REVIEW] <profile name here>"
labels: [gh sponsor review, live stream review]
body:
  - type: input
    id: link
    attributes:
      label: GitHub Sponsor profile link
    validations:
      required: true
   - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](#)
        Feel free to check out other cool repositories of the SpaceYaTech Community [here](https://github.com/SpaceyaTech)